version: 2.1
orbs:
  node: circleci/node@5.0.2

workflows:
  build_and_test:
    jobs:
      - build_and_test

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run tests
          command: yarn test
